-- This file should undo anything in `up.sql`
DROP FUNCTION IF EXISTS manage_updated_at;
DROP FUNCTION IF EXISTS set_updated_at;
DROP TABLE transactions;
DROP TABLE likes;
DROP TABLE boosts;
DROP TABLE _mentions;
DROP TABLE followers;
DROP TABLE printer;
DROP TABLE note;
DROP TABLE file;
DROP TABLE model;
DROP TABLE account;
DROP TABLE profile;
DROP TYPE modified_scale;
DROP TYPE event_audience;
DROP TYPE model_license;
DROP TABLE IF EXISTS instances;
DROP TABLE jobs;
DROP TYPE job_status;
DROP TYPE job_type;
DROP FUNCTION IF EXISTS notify_worker_update;
DROP FUNCTION IF EXISTS notify_past_retry;
DROP EXTENSION pg_uuidv7;
