use prusaslicer_macros::CommandOptions;
use std::fmt;

pub struct NoExtraParam;
impl fmt::Display for NoExtraParam {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("") // Writes an empty string
    }
}

pub struct TwoArgs(i32, i32);

impl fmt::Display for TwoArgs {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{},{}", self.0, self.1)
    }
}

pub struct TwoFloatArgs(i32, i32);

impl fmt::Display for TwoFloatArgs {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{},{}", self.0, self.1)
    }
}

pub struct ThreeArgs(i32, i32, i32);

impl fmt::Display for crate::ThreeArgs {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{},{},{}", self.0, self.1, self.2)
    }
}

#[derive(CommandOptions, Default)]
pub struct PrusaSlicerOptions {
    pub export_3mf: Option<NoExtraParam>,
    pub export_amf: Option<NoExtraParam>,
    pub export_gcode: Option<NoExtraParam>,
    pub export_obj: Option<NoExtraParam>,
    pub export_stl: Option<NoExtraParam>,
    pub save: Option<String>,
    pub slice: Option<NoExtraParam>,
    pub align_xy: Option<TwoArgs>,
    pub center: Option<TwoArgs>,
    pub cut: Option<i32>,
    pub delete_after_load: Option<NoExtraParam>,
    pub dont_arrange: Option<NoExtraParam>,
    pub duplicate: Option<i32>,
    pub duplicate_grid: Option<TwoArgs>,
    pub ensure_on_bed: Option<NoExtraParam>,
    pub merge: Option<NoExtraParam>,
    pub repair: Option<NoExtraParam>,
    pub rotate: Option<i32>,
    pub rotate_x: Option<i32>,
    pub rotate_y: Option<i32>,
    pub scale: Option<i32>,
    pub scale_to_fit: Option<ThreeArgs>,
    pub split: Option<NoExtraParam>,
    pub datadir: Option<String>,
    pub ignore_nonexistent_config: Option<NoExtraParam>,
    pub load: Option<String>,
    pub loglevel: Option<i32>,
    pub output: Option<String>,
    pub single_instance: Option<NoExtraParam>,
    pub arc_fitting: Option<NoExtraParam>,
    pub autoemit_temperature_commands: Option<NoExtraParam>,
    pub avoid_crossing_curled_overhangs: Option<NoExtraParam>,
    pub avoid_crossing_perimeters: Option<NoExtraParam>,
    pub bed_custom_model: Option<String>,
    pub bed_custom_texture: Option<String>,
    pub bed_shape: Option<String>,
    pub bed_temperature: Option<i32>,
    pub before_layer_gcode: Option<String>,
    pub between_objects_gcode: Option<String>,
    pub binary_gcode: Option<NoExtraParam>,
    pub bridge_acceleration: Option<i32>,
    pub bridge_fan_speed: Option<i32>,
    pub color_change_gcode: Option<String>,
    pub colorprint_heights: Option<i32>,
    pub complete_objects: Option<NoExtraParam>,
    pub cooling: Option<NoExtraParam>,
    pub cooling_tube_length: Option<i32>,
    pub cooling_tube_retraction: Option<i32>,
    pub default_acceleration: Option<i32>,
    pub deretract_speed: Option<i32>,
    pub disable_fan_first_layers: Option<i32>,
    pub draft_shield: Option<NoExtraParam>,
    pub duplicate_distance: Option<i32>,
    pub enable_dynamic_fan_speed: Option<NoExtraParam>,
    pub end_filament_gcode: Option<String>,
    pub end_gcode: Option<String>,
    pub external_perimeter_acceleration: Option<i32>,
    pub extra_loading_move: Option<i32>,
    pub extra_clearance_height: Option<i32>,
    pub extruder_clearance_radius: Option<i32>,
    pub extruder_colour: Option<String>,
    pub extruder_offset: Option<String>,
    pub extrusion_axis: Option<String>,
    pub extrusion_multiplier: Option<i32>,
    pub fan_always_on: Option<NoExtraParam>,
    pub fan_below_layer_time: Option<i32>,
    pub filament_colour: Option<String>,
    pub filament_cooling_final_speed: Option<i32>,
    pub filament_cooling_initial_speed: Option<i32>,
    pub filament_cooling_moves: Option<i32>,
    pub filament_cost: Option<i32>,
    pub filament_density: Option<i32>,
    pub filament_deretract_speed: Option<i32>,
    pub filament_diameter: Option<i32>,
    pub filament_load_time: Option<i32>,
    pub filament_loading_speed: Option<i32>,
    pub filament_loading_speed_start: Option<i32>,
    pub filament_max_volumetric_speed: Option<i32>,
    pub filament_minimal_purge_no_wipe_tower: Option<i32>,
    pub filament_multitool_ramming: Option<NoExtraParam>,
    pub filament_multitool_ramming_flow: Option<i32>,
    pub filament_multitool_ramming_volume: Option<i32>,
    pub filament_notes: Option<String>,
    pub filament_ramming_parameters: Option<String>,
    pub filament_retract_before_travel: Option<i32>,
    pub filament_retract_before_wipe: Option<i32>,
    pub filament_retract_before_layer_change: Option<NoExtraParam>,
    pub filament_retract_length: Option<i32>,
    pub filament_retract_length_toolchange: Option<i32>,
    pub filament_retract_lift: Option<i32>,
    pub filament_retract_lift_above: Option<i32>,
    pub filament_retract_lift_below: Option<i32>,
    pub filament_retract_restart_extra: Option<i32>,
    pub filament_retract_restart_extra_toolchange: Option<i32>,
    pub filament_retract_speed: Option<i32>,
    pub filament_soluble: Option<NoExtraParam>,
    pub filament_spool_weight: Option<i32>,
    pub filament_toolchange_delay: Option<i32>,
    pub filament_travel_lift_before_obstacles: Option<NoExtraParam>,
    pub filament_travel_max_lift: Option<i32>,
    pub filament_travel_ramping_lift: Option<NoExtraParam>,
    pub filament_travel_slope: Option<i32>,
    pub filament_type: Option<String>,
    pub filament_unload_time: Option<i32>,
    pub filament_unloading_speed: Option<i32>,
    pub filament_unloading_speed_start: Option<i32>,
    pub filament_wipe: Option<NoExtraParam>,
    pub first_layer_acceleration: Option<i32>,
    pub first_layer_acceleration_over_draft: Option<i32>,
    pub first_layer_bed_temperature: Option<i32>,
    pub first_layer_speed: Option<i32>,
    pub first_layer_speed_over_draft: Option<i32>,
    pub first_layer_temperature: Option<i32>,
    pub full_fan_speed_layer: Option<i32>,
    pub gcode_comments: Option<NoExtraParam>,
    pub gcode_flavor: Option<String>,
    pub gcode_label_objects: Option<NoExtraParam>,
    pub gcode_resolution: Option<i32>,
    pub gcode_substitutions: Option<String>,
    pub high_current_on_filament_swap: Option<NoExtraParam>,
    pub infill_acceleration: Option<i32>,
    pub infill_first: Option<NoExtraParam>,
    pub after_layer_gcode: Option<String>,
    pub max_fan_speed: Option<i32>,
    pub max_layer_height: Option<i32>,
    pub max_print_height: Option<i32>,
    pub max_print_speed: Option<i32>,
    pub max_volumetric_extrusion_rate_slope_negative: Option<i32>,
    pub max_volumetric_extrusion_rate_slope_positive: Option<i32>,
    pub max_volumetric_speed: Option<i32>,
    pub min_fan_speed: Option<i32>,
    pub min_layer_height: Option<i32>,
    pub min_print_speed: Option<i32>,
    pub min_skirt_length: Option<i32>,
    pub notes: Option<String>,
    pub nozzle_diameter: Option<f32>,
    pub only_retract_when_crossing_perimeters: Option<NoExtraParam>,
    pub ooze_prevention: Option<NoExtraParam>,
    pub output_filename_format: Option<String>,
    pub overhang_fan_speed_0: Option<i32>,
    pub overhang_fan_speed_1: Option<i32>,
    pub overhang_fan_speed_2: Option<i32>,
    pub overhang_fan_speed_3: Option<i32>,
    pub parking_pos_retraction: Option<i32>,
    pub pause_print_gcode: Option<String>,
    pub perimeter_acceleration: Option<i32>,
    pub post_process: Option<String>,
    pub preset_name: Option<String>,
    pub preset_names: Option<String>,
    pub printer_notes: Option<String>,
    pub printer_technology: Option<String>,
    pub remaining_times: Option<NoExtraParam>,
    pub resolution: Option<i32>,
    pub retract_before_travel: Option<i32>,
    pub retract_before_wipe: Option<i32>,
    pub retract_length: Option<i32>,
    pub retract_length_toolchange: Option<i32>,
    pub retract_lift: Option<i32>,
    pub retract_lift_above: Option<i32>,
    pub retract_restart_extra: Option<i32>,
    pub retract_restart_extra_toolchange: Option<i32>,
    pub retract_speed: Option<i32>,
    pub silent_mode: Option<NoExtraParam>,
    pub single_extruder_multi_material: Option<NoExtraParam>,
    pub single_extruder_multi_material_priming: Option<NoExtraParam>,
    pub skirt_distance: Option<i32>,
    pub skirt_height: Option<i32>,
    pub skirts: Option<i32>,
    pub slowdown_below_layer_time: Option<i32>,
    pub solid_infill_acceleration: Option<i32>,
    pub solid_layers: Option<i32>,
    pub solid_min_thickness: Option<i32>,
    pub spiral_vase: Option<i32>,
    pub staggered_inner_seams: Option<NoExtraParam>,
    pub standby_temperature_delta: Option<i32>,
    pub start_filament_gcode: Option<String>,
    pub start_gcode: Option<String>,
    pub temperature: Option<i32>,
    pub template_custom_gcode: Option<String>,
    pub thumbnails: Option<String>,
    pub thumbnails_format: Option<String>,
    pub toolchange_gcode: Option<String>,
    pub top_solid_infill_acceleration: Option<i32>,
    pub travel_acceleration: Option<i32>,
    pub travel_lift_before_obstacle: Option<NoExtraParam>,
    pub travel_max_lift: Option<i32>,
    pub travel_ramping_lift: Option<NoExtraParam>,
    pub travel_slope: Option<i32>,
    pub travel_speed: Option<i32>,
    pub travel_speed_z: Option<i32>,
    pub use_firmware_retraction: Option<NoExtraParam>,
    pub use_relative_e_distances: Option<NoExtraParam>,
    pub use_volumetric_e: Option<NoExtraParam>,
    pub variable_layer_height: Option<NoExtraParam>,
    pub wipe: Option<NoExtraParam>,
    pub wipe_tower: Option<NoExtraParam>,
    pub wipe_tower_bridging: Option<i32>,
    pub wipe_tower_brim_width: Option<f32>,
    pub wipe_tower_cone_angle: Option<i32>,
    pub wipe_tower_extra_spacing: Option<i32>,
    pub wipe_tower_no_sparse_layers: Option<NoExtraParam>,
    pub wipe_tower_rotation_angle: Option<i32>,
    pub wipe_tower_width: Option<i32>,
    pub wipe_tower_x: Option<i32>,
    pub wipe_toerw_y: Option<i32>,
    pub wiping_volumes_extruders: Option<String>,
    pub wiping_volumes_matrix: Option<String>,
    pub z_offset: Option<f32>,
    pub bridge_flow_ratio: Option<f32>,
    pub elefant_foot_compensation: Option<f32>,
    pub infill_anchor: Option<i32>,
    pub infill_anchor_max: Option<i32>,
    pub infill_overlap: Option<i32>,
    pub min_bead_with: Option<i32>,
    pub min_feature_size: Option<i32>,
    pub mmu_segmented_region_interlocking_depth: Option<i32>,
    pub mmu_segmented_region_max_width: Option<i32>,
    pub slice_closing_radius: Option<f32>,
    pub slicing_mode: Option<String>,
    pub wall_distribution_count: Option<i32>,
    pub wall_transition_angle: Option<i32>,
    pub wall_transition_filter_deviation: Option<i32>,
    pub wall_transition_length: Option<i32>,
    pub xy_size_compensation: Option<f32>, // or just int
    pub extruder: Option<i32>,
    pub infill_extruder: Option<i32>,
    pub perimeter_extruder: Option<i32>,
    pub solid_infill_extruder: Option<i32>,
    pub support_material_extruder: Option<i32>,
    pub support_material_interface_extruder: Option<i32>,
    pub wipe_tower_extruder: Option<i32>,
    pub external_perimeter_extrusion_width: Option<String>, // % or mm
    pub extrusion_width: Option<String>,                    // % or mm
    pub first_layer_extrusion_width: Option<String>,        // % or mm
    pub infill_extrusion_width: Option<String>,             // % or mm
    pub perimeter_extrusion_width: Option<String>,          // % or mm
    pub solid_infill_extrusion_width: Option<String>,       // % or mm
    pub support_material_extrusion_width: Option<String>,   // % or mm
    pub top_infill_extrusion_width: Option<String>,         // % or mm
    pub fuzzy_skin: Option<NoExtraParam>,
    pub fuzzy_skin_point_dist: Option<f32>,
    pub fuzzy_skin_thickness: Option<f32>,
    pub bottom_fill_pattern: Option<String>,
    pub bridge_angle: Option<i32>,
    pub fill_angle: Option<i32>,
    pub fill_density: Option<i32>,
    pub fill_pattern: Option<String>,
    pub infill_every_layers: Option<i32>,
    pub solid_infill_below_area: Option<i32>,
    pub solid_infill_every_layers: Option<i32>,
    pub top_fill_pattern: Option<String>,
    pub ironing: Option<NoExtraParam>,
    pub ironing_flowrate: Option<i32>,
    pub ironing_spacing: Option<f32>,
    pub ironing_type: Option<String>,
    pub avoid_crossing_perimeters_max_detour: Option<i32>,
    pub bottom_solid_layers: Option<i32>,
    pub bottom_solid_min_thickness: Option<i32>,
    pub external_perimeters_first: Option<NoExtraParam>,
    pub extra_perimeters: Option<NoExtraParam>,
    pub extra_perimeters_on_overhang: Option<NoExtraParam>,
    pub first_layer_height: Option<f32>,
    pub gap_fill_enabled: Option<NoExtraParam>,
    pub interface_shells: Option<NoExtraParam>,
    pub layer_height: Option<f32>,
    pub overhangs: Option<NoExtraParam>,
    pub perimeter_generator: Option<String>,
    pub perimeters: Option<i32>,
    pub seam_position: Option<String>,
    pub thick_bridges: Option<NoExtraParam>,
    pub thin_walls: Option<NoExtraParam>,
    pub top_solid_layers: Option<i32>,
    pub top_solid_min_thickness: Option<f32>,
    pub machine_limits_usage: Option<String>,
    pub machine_max_acceleration_e: Option<TwoArgs>,
    pub machine_max_acceleration_extruding: Option<TwoArgs>,
    pub machine_max_acceleration_retracting: Option<TwoArgs>,
    pub machine_max_acceleration_travel: Option<TwoArgs>,
    pub machine_max_acceleration_x: Option<TwoArgs>,
    pub machine_max_acceleration_y: Option<TwoArgs>,
    pub machine_max_acceleration_z: Option<TwoArgs>,
    pub machine_max_feedrate_e: Option<TwoArgs>,
    pub machine_max_feedrate_x: Option<TwoArgs>,
    pub machine_max_feedrate_y: Option<TwoArgs>,
    pub machine_max_feedrate_z: Option<TwoArgs>,
    pub machine_max_jerk_e: Option<TwoFloatArgs>,
    pub machine_max_jerk_x: Option<TwoFloatArgs>,
    pub machine_max_jerk_y: Option<TwoFloatArgs>,
    pub machine_max_jerk_z: Option<TwoFloatArgs>,
    pub machine_min_extruding_rate: Option<i32>,
    pub machine_min_travel_rate: Option<i32>,
    pub brim_separation: Option<i32>,
    pub brim_type: Option<String>,
    pub brim_width: Option<f32>,
    pub bridge_speed: Option<i32>,
    pub enable_dynamic_overhang_speeds: Option<NoExtraParam>,
    pub external_perimeters_speed: Option<String>, // % or mm/s
    pub gap_fill_speed: Option<i32>,
    pub infill_speed: Option<i32>,
    pub ironing_speed: Option<i32>,
    pub overhang_speed_0: Option<String>, // % or mm/s
    pub overhang_speed_1: Option<String>, // % or mm/s
    pub overhang_speed_2: Option<String>, // % or mm/s
    pub overhang_speed_3: Option<String>, // % or mm/s
    pub perimeter_speed: Option<i32>,
    pub small_perimeter_speed: Option<String>,  // % or mm/s
    pub solid_infill_speed: Option<String>,     // % or mm/s
    pub top_solid_infill_speed: Option<String>, // % or mm/s
    pub dont_support_bridges: Option<NoExtraParam>,
    pub raft_contact_distance: Option<f32>,
    pub raft_expansion: Option<f32>,
    pub raft_first_layer_density: Option<i32>,
    pub raft_first_layer_expansion: Option<i32>,
    pub raft_layers: Option<i32>,
    pub support_material: Option<NoExtraParam>,
    pub support_material_angle: Option<i32>,
    pub support_material_auto: Option<NoExtraParam>,
    pub support_material_bottom_contact_distance: Option<f32>,
    pub support_material_bottom_interface_layers: Option<i32>,
    pub support_material_closing_radius: Option<i32>,
    pub support_material_contact_distance: Option<f32>,
    pub support_material_enforce_layers: Option<i32>,
    pub support_material_interface_contact_loops: Option<NoExtraParam>,
    pub support_material_interface_layers: Option<i32>,
    pub support_material_interface_patterns: Option<String>,
    pub support_material_interface_spacing: Option<f32>,
    pub support_material_pattern: Option<String>,
    pub support_material_spacing: Option<f32>,
    pub support_material_speed: Option<i32>,
    pub support_material_style: Option<String>,
    pub support_material_synchronize_layers: Option<NoExtraParam>,
    pub support_material_threshold: Option<i32>,
    pub support_material_with_sheath: Option<NoExtraParam>,
    pub support_material_xy_spacing: Option<String>, // % or mm/s
    pub support_tree_angle_slow: Option<i32>,
    pub support_tree_branch_diameter: Option<f32>,
    pub support_tree_branch_diameter_double_wall: Option<f32>,
    pub support_tree_branch_distance: Option<f32>,
    pub support_tree_tip_diameter: Option<f32>,
    pub support_tree_top_rate: Option<i32>,
    pub wipe_into_infill: Option<NoExtraParam>,
    pub wipe_into_objects: Option<NoExtraParam>,
}

fn main() {
    /*    let options = PrusaSlicerOptions {
        align_xy: Some(NoExtraParam),
        datadir: Some("hallo".to_string()),
        scale_to_fit: Some(ThreeArgs(10,10,10))
        // ..Default::default() // Add more options as needed
    };*/

    // let command_args = options.to_command_args();
    // println!("Command args: {:?}", command_args);
}
